### ISSUE TITLE
Onboarding (Dev) - Set Watchers on Extra DSRV Cloud for long Term test

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz-plugin-watchers#16]
- Parents: #3 

---

**Comment by xellos00** [comment]
@meetrick @kim201212 
Can you set up a machine (DSRV CLOUD) to deploy this?

**Comment by heejin-github** [comment]
> @meetrick @kim201212 Can you set up a machine (DSRV CLOUD) to deploy this?

@xellos00 
Please open an issue on dsrv-cloud repo.
https://github.com/dsrvlabs/dsrv-cloud/issues/new/choose

**Comment by xellos00** [comment]
> https://github.com/dsrvlabs/dsrv-cloud/issues/new/choose



> > @meetrick @kim201212 Can you set up a machine (DSRV CLOUD) to deploy this?
> 
> @xellos00 Please open an issue on dsrv-cloud repo. https://github.com/dsrvlabs/dsrv-cloud/issues/new/choose

@meetrick @kim201212 
Can you guys handle to created an issue as @heejin-github requested above?

**Comment by meetrick** [comment]
@xellos00 I did it.

- https://github.com/dsrvlabs/dsrv-cloud/issues/211

**Comment by xellos00** [comment]
# Test is started and connected to GCP for VATZ working Status

```
root@monitoring-node-watcher-dc-sel2:~/dsrv/script# ls
vatz_install.sh  vatz_start.sh
root@monitoring-node-watcher-dc-sel2:~/dsrv/script# bash vatz_start.sh

VATZ_PATH=/root/dsrv/vatz
LOG_PATH=/root/dsrv/vatz_setup/log

WATCHER_COSMOS_PORT=10001
OSMOSIS_HEX=5F999A4BE254869925A7F2FEA04D7B3B836CFF0B
RPC_URL=https://rpc.osmosis.zone

cd $VATZ_PATH

./vatz plugin start --plugin watcher_cosmos --args "-port $WATCHER_COSMOS_PORT -valoperAddr $OSMOSIS_HEX -rpcURI $RPC_URL" --log $LOG_PATH/watcher_cosmos.log
2024-08-06T23:30:55Z INF Start plugin watcher_cosmos -port 10001 -valoperAddr 5F999A4BE254869925A7F2FEA04D7B3B836CFF0B -rpcURI https://rpc.osmosis.zone module=plugin
2024-08-06T23:30:55Z INF Plugin watcher_cosmos is successfully started. module=plugin
./vatz start --config /root/dsrv/vatz_setup/vatz_config.yaml >> $LOG_PATH/vatz.log 2>&1 &

echo "true"
true
root@monitoring-node-watcher-dc-sel2:~/dsrv/script#
```

**Comment by xellos00** [comment]
@meetrick 
I aplogize for dealy to set up, and give you notice little bit late, but osmosis validator watcher has been set up and report to GCP 

<img width="1506" alt="image" src="https://github.com/user-attachments/assets/36cef6f4-4c13-45da-9811-43a3881c3a30">
<img width="1482" alt="image" src="https://github.com/user-attachments/assets/5fc5cff9-8c53-4a1f-bb0a-17bc8949c422">
<img width="1021" alt="image" src="https://github.com/user-attachments/assets/7c6eaf6e-50d5-44fe-a94d-8cc0bf84eb80">

**Comment by xellos00** [comment]
long term test was finished via issue, It's been tested and fully function more than 3 weeks. 
- https://github.com/dsrvlabs/node-watcher-project/issues/22
