### ISSUE TITLE
Onboarding (Test) - Test planning

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz-plugin-watchers#5]
- Parents: #3 

---

This is issue to handle our test for this plugins for cosmos chains.  
Tester: 
- @xellos00 
- @kim201212 
- @meetrick 

---

**Comment by xellos00** [comment]
@kim201212
I think we need to have a meeting to discuss how we are going to test, or little demo on this?
Can you set up a meeting me and @meetrick for the test scenarios?  
I have plan to how we are going to test, but it's better to have a meeting with it first.

**Comment by meetrick** [comment]
> @kim201212 I think we need to have a meeting to discuss how we are going to test, or little demo on this? Can you set up a meeting me and @meetrick for the test scenarios? I have plan to how we are going to test, but it's better to have a meeting with it first.

- @xellos00 I am unavailable from 2024-06-26T03:30:00 to 09:00:00 UTC, all other times are available.

**Comment by kim201212** [comment]
@xellos00 @meetrick 
I will send invitation to you guys! And then let's discuss.

**Comment by xellos00** [comment]
> @xellos00 @meetrick I will send invitation to you guys! And then let's discuss.

<img width="629" alt="image" src="https://github.com/dsrvlabs/vatz-plugin-watcher-cosmos/assets/6308023/6243e829-6d2f-4a47-accb-9af698d02a38">

Can you share our meeting record link on this issue after we have a meeting?

**Comment by kim201212** [comment]
1. `README.md`에 pubkey를 찾아서 넣는게 맞는거같음.

**Comment by xellos00** [comment]
- Flags
   - addr  
   - port number 
   - warning 4  (count)
   - Critical  5 (count)
   - RPC URL (ATN service alike)
   - pub_key 
   
   example) 
   - refer to https://github.com/dsrvlabs/vatz-plugin-sei?tab=readme-ov-file#command-line-arguments
  
   ```
   Usage of node_active_status:
  -addr string
    	Listening address (default "127.0.0.1")
  -port int
    	Listening port (default 10004)
  -rpcURI string
    	CosmosHub RPC URI Address (default "http://localhost:1317")
  -valoperAddr string
    	CosmosHub validator operator address
   ```

**Comment by xellos00** [comment]
# Finish all development for following protocos by 2024-7-2
- [ ] osmosis
- [ ] cosmos

# Finish all development for following protocos by 2024-7-9
- [ ] rest of protocol in cosmos

**Comment by kim201212** [comment]
## Meeting Record
- https://drive.google.com/file/d/1hfI2TZgyOVX0GYuQfK6WGIjthkn_kuT_/view

**Comment by xellos00** [comment]
> * https://drive.google.com/file/d/1hfI2TZgyOVX0GYuQfK6WGIjthkn_kuT_/view

Thanks for update, its access limited for only member of DSRV. Appreciate it.

**Comment by kim201212** [comment]
@xellos00 @meetrick 

Please test the code.

- Run the commands below on the server with vatz:

```
$ ./vatz plugin install https://github.com/dsrvlabs/vatz-plugin-watcher-cosmos/plugins/watcher_cosmos watcher_cosmos
$ ./vatz plugin start --plugin watcher_cosmos --args "-validator=51FD33F85A311FD27B36A620A7B9A40BF4839533 -rpcurl=https://rpc.testnet.osmosis.zone"
```

- and then kill the osmosis testnet validator.

**Comment by xellos00** [comment]
> @xellos00 @meetrick
> 
> Please test the code.
> 
> * Run the commands below on the server with vatz:
> 
> ```
> $ ./vatz plugin install https://github.com/dsrvlabs/vatz-plugin-watcher-cosmos/plugins/watcher_cosmos watcher_cosmos
> $ ./vatz plugin start --plugin watcher_cosmos --args "-validator=51FD33F85A311FD27B36A620A7B9A40BF4839533 -rpcurl=https://rpc.testnet.osmosis.zone"
> ```
> 
> * and then kill the osmosis testnet validator.

# Test by @meetrick @xellos00 
- [x] #8 
- [x] #9

**Comment by xellos00** [comment]
@meetrick @kim201212 
- https://github.com/dsrvlabs/vatz-plugin-watcher-cosmos/pull/12
Please, review it, once you guys review and approve it, 
I will change this repo name from `vatz-plugin-watcher-cosmos` to `vatz-plugin-watchers` with another PR. 

Please, let me know if there's any trouble or concern.
